stack_name: base_foundation

global_backend_config:
  bucket: "terraform-state20220711040913053000000001"
  key: "state-dev/terraform.tfstate"
  region: "us-east-1"
  encrypt: true
  kms_key_id: "alias/terraform-bucket-key"
  dynamodb_table: "terraform-state"

global_vars:
  environment: "dev"
  ansible_instance_type: "t3.small"
  instance_type: "t3.small"
  db_instance_type: "db.t3.small"
  vpc_cidr: "10.1.0.0/16"
  private_subnet_a: "10.1.1.0/24"
  public_subnet_a: "10.1.101.0/24"
  private_subnet_b: "10.1.2.0/24"
  public_subnet_b: "10.1.102.0/24"
  private_subnet_c: "10.1.3.0/24"
  public_subnet_c: "10.1.103.0/24"
  database_subnet_a: "10.1.201.0/24"
  database_subnet_b: "10.1.202.0/24"
  database_subnet_c: "10.1.203.0/24"
  rds_allocated_storage: 10
  rds_max_allocated_storage: 20
