{
 "title": "AWS Lambda",
 "description": "Visualize Amazon Lambda metrics",
 "tags": [
  "cloudwatch-integration",
  "terraform"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(aws_lambda_info, scrape_job)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(aws_lambda_invocations_sum, region)"
   },
   {
    "name": "function_name",
    "label": "Function name",
    "query": "label_values(aws_lambda_invocations_sum{scrape_job=~\"$job\", region=~\"$region\"}, dimension_FunctionName)"
   },
   {
    "name": "resource",
    "label": "Resource",
    "query": "label_values(aws_lambda_invocations_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_FunctionName=~\"$function_name\"}, dimension_Resource)"
   },
   {
    "name": "executed_version",
    "label": "Executed Version",
    "query": "label_values(aws_lambda_invocations_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_FunctionName=~\"$function_name\", dimension_Resource=~\"$resource\"}, dimension_ExecutedVersion)"
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Showing metrics only for AWS resources that have tags assigned to them. For more information, see [Amazon CloudWatch Metrics for Amazon Lambda](https://docs.aws.amazon.com/lambda/latest/dg/monitoring-metrics.html).\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Invocations",
   "type": "graph",
   "description": "The number of times your function code is executed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_FunctionName) (aws_lambda_invocations_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_FunctionName=~\"$function_name\", dimension_Resource=~\"$resource\", dimension_ExecutedVersion=~\"$executed_version\"})",
     "legendFormat": "{{dimension_FunctionName}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "The number of invocations that result in a function error.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_FunctionName) (aws_lambda_errors_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_FunctionName=~\"$function_name\", dimension_Resource=~\"$resource\", dimension_ExecutedVersion=~\"$executed_version\"})",
     "legendFormat": "{{dimension_FunctionName}}"
    }
   ]
  },
  {
   "title": "Throttles",
   "type": "graph",
   "description": "The number of invocation requests that are throttled.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_FunctionName) (aws_lambda_throttles_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_FunctionName=~\"$function_name\", dimension_Resource=~\"$resource\", dimension_ExecutedVersion=~\"$executed_version\"})",
     "legendFormat": "{{dimension_FunctionName}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "The time that your function code spends processing an event.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_FunctionName) (aws_lambda_duration_p90{scrape_job=~\"$job\", region=~\"$region\", dimension_FunctionName=~\"$function_name\", dimension_Resource=~\"$resource\", dimension_ExecutedVersion=~\"$executed_version\"})",
     "legendFormat": "{{dimension_FunctionName}} (p90)"
    },
    {
     "expr": "sum by (dimension_FunctionName) (aws_lambda_duration_minimum{scrape_job=~\"$job\", region=~\"$region\", dimension_FunctionName=~\"$function_name\", dimension_Resource=~\"$resource\", dimension_ExecutedVersion=~\"$executed_version\"})",
     "legendFormat": "{{dimension_FunctionName}} (min)"
    },
    {
     "expr": "sum by (dimension_FunctionName) (aws_lambda_duration_maximum{scrape_job=~\"$job\", region=~\"$region\", dimension_FunctionName=~\"$function_name\", dimension_Resource=~\"$resource\", dimension_ExecutedVersion=~\"$executed_version\"})",
     "legendFormat": "{{dimension_FunctionName}} (max)"
    }
   ]
  }
 ]
}