{
 "title": "AWS ECS",
 "description": "Visualize Amazon ECS metrics",
 "tags": [
  "cloudwatch-integration",
  "terraform"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(aws_ecs_info, scrape_job)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(aws_ecs_cpuutilization_average, region)"
   },
   {
    "name": "cluster_name",
    "label": "ClusterName",
    "query": "label_values(aws_ecs_cpuutilization_average{scrape_job=~\"$job\", region=~\"$region\"}, dimension_ClusterName)"
   },
   {
    "name": "service_name",
    "label": "ServiceName",
    "query": "label_values(aws_ecs_cpuutilization_average{scrape_job=~\"$job\", region=~\"$region\", dimension_ClusterName=~\"$cluster_name\"}, dimension_ServiceName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Showing metrics only for AWS ECS clusters and tasks that have tags assigned to them. For more information, see [Amazon ECS CloudWatch metrics](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html).\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ecs_cpuutilization_average{scrape_job=~\"$job\", region=~\"$region\", dimension_ClusterName=~\"$cluster_name\", dimension_ServiceName=~\"$service_name\"}",
     "legendFormat": "{{dimension_ClusterName}}/{{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ecs_memory_utilization_average{scrape_job=~\"$job\", region=~\"$region\", dimension_ClusterName=~\"$cluster_name\", dimension_ServiceName=~\"$service_name\"}",
     "legendFormat": "{{dimension_ClusterName}}/{{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "CPU reservation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ecs_cpureservation_average{scrape_job=~\"$job\", region=~\"$region\", dimension_ClusterName=~\"$cluster_name\", dimension_ServiceName=~\"$service_name\"}",
     "legendFormat": "{{dimension_ClusterName}}/{{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "Memory reservation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ecs_memory_reservation_average{scrape_job=~\"$job\", region=~\"$region\", dimension_ClusterName=~\"$cluster_name\", dimension_ServiceName=~\"$service_name\"}",
     "legendFormat": "{{dimension_ClusterName}}/{{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "GPU reservation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ecs_gpureservation_average{scrape_job=~\"$job\", region=~\"$region\", dimension_ClusterName=~\"$cluster_name\", dimension_ServiceName=~\"$service_name\"}",
     "legendFormat": "{{dimension_ClusterName}}/{{dimension_ServiceName}}"
    }
   ]
  }
 ]
}