{
 "title": "AWS EC2",
 "description": "Visualize Amazon EC2 metrics",
 "tags": [
  "cloudwatch-integration",
  "terraform"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(aws_ec2_info, scrape_job)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(aws_ec2_cpuutilization_maximum, region)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(aws_ec2_cpuutilization_maximum{scrape_job=~\"$job\", region=~\"$region\"}, dimension_InstanceId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Showing metrics only for AWS resources that have tags assigned to them. For more information, see [Amazon CloudWatch Metrics for Amazon EC2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html).\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ec2_cpuutilization_maximum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
     "legendFormat": "{{dimension_InstanceId}}"
    }
   ]
  },
  {
   "title": "Average network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bps", "label": "bytes in (+) / out (-)" }
   ],
   "targets": [
    {
     "expr": "aws_ec2_network_in_average{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
     "legendFormat": "{{dimension_InstanceId}} inbound"
    },
    {
     "expr": "aws_ec2_network_out_average{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
     "legendFormat": "{{dimension_InstanceId}} outbound"
    }
   ]
  },
  {
   "title": "Network details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Inbound network traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_network_in_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
       "legendFormat": "{{dimension_InstanceId}}"
      }
     ]
    },
    {
     "title": "Outbound network traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_network_out_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
       "legendFormat": "{{dimension_InstanceId}}"
      }
     ]
    },
    {
     "title": "Inbound network packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_network_packets_in_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
       "legendFormat": "{{dimension_InstanceId}}"
      }
     ]
    },
    {
     "title": "Outbound network packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_network_packets_out_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
       "legendFormat": "{{dimension_InstanceId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
     "content": "The following metrics are reported for EC2 Instance Store Volumes. For Amazon EBS volumes, see the EBS dashboard."
    },
    {
     "title": "Disk reads (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_disk_read_bytes_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
       "legendFormat": "{{dimension_InstanceId}}"
      }
     ]
    },
    {
     "title": "Disk writes (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_disk_write_bytes_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
       "legendFormat": "{{dimension_InstanceId}}"
      }
     ]
    },
    {
     "title": "Disk read (operations)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_disk_read_ops_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
       "legendFormat": "{{dimension_InstanceId}}"
      }
     ]
    },
    {
     "title": "Disk write (operations)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_disk_write_ops_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
       "legendFormat": "{{dimension_InstanceId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Status checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Status check failed (system)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_status_check_failed_system_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
       "legendFormat": "{{dimension_InstanceId}}"
      }
     ]
    },
    {
     "title": "Status check failed (instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_status_check_failed_instance_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
       "legendFormat": "{{dimension_InstanceId}}"
      }
     ]
    },
    {
     "title": "Status check failed (all)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_ec2_status_check_failed_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_InstanceId=~\"$instance\"}",
       "legendFormat": "{{dimension_InstanceId}}"
      }
     ]
    }
   ]
  }
 ]
}