{
 "title": "MLT Dashboard (Cloud)",
 "tags": [ "terraform" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service_name", "label": "Service name", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name) (sum by(service_name) (rate(traces_spanmetrics_latency_sum{service_name=~\"$service_name\"}[$__rate_interval])) / sum by(service_name) (rate(traces_spanmetrics_latency_count{service_name=~\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Overall Error %age",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(traces_spanmetrics_calls_total{service_name=~\"$service_name\", status_code=\"STATUS_CODE_ERROR\"}[5m]))/sum(increase(traces_spanmetrics_calls_total{service_name=~\"$service_name\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Error Percentages by Target",
   "type": "stat",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (service_name)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service_name\"}[5m])))/(sum by (service_name)(increase(traces_spanmetrics_calls_total{status_code!=\"\",service_name=~\"$service_name\"}[5m]))) * 100",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "HTTP Status codes by Service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(http_status_code, service_name) (rate(traces_spanmetrics_calls_total{job=\"span-metrics\", span_kind!=\"SPAN_KIND_UNSPECIFIED\", service_name=~\"$service_name\"}[$__rate_interval]))",
     "legendFormat": " service {{service_name}}: {{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code, service_name) (rate(traces_spanmetrics_calls_total{job=\"span-metrics\", span_kind=\"SPAN_KIND_UNSPECIFIED\", service_name=~\"$service_name\"}[$__rate_interval]))",
     "legendFormat": " service {{service_name}}: unspecified"
    }
   ]
  },
  {
   "title": "Top 25 Highest Endpoint Latencies Over Last 10 Minutes",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(25, sum by (http_method,http_target,service_name,http_status_code)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\", service_name=~\"$service_name\"}[10m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\", service_name=~\"$service_name\"}[10m])))"
    }
   ]
  },
  {
   "title": "All Endpoint Latencies in ms (Last 10 mins)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (http_method,http_target,http_status_code)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\", service_name=~\"$service_name\"}[10m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\", service_name=~\"$service_name\"}[10m]))",
     "legendFormat": "{{http_method}} {{http_target}} / {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Response Latencies (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service_name=~\"$service_name\"}[$__rate_interval])) by (le, beast))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=~\"$service_name\"}[$__rate_interval])) by (le, beast))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traces_spanmetrics_latency_bucket{service_name=~\"$service_name\"}[$__rate_interval])) by (le, beast))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.85, sum(rate(traces_spanmetrics_latency_bucket{service_name=~\"$service_name\"}[$__rate_interval])) by (le, beast))",
     "legendFormat": "85th Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(traces_spanmetrics_latency_bucket{service_name=~\"$service_name\"}[$__rate_interval])) by (le, beast))",
     "legendFormat": "75th Percentile"
    },
    {
     "expr": "histogram_quantile(0.65, sum(rate(traces_spanmetrics_latency_bucket{service_name=~\"$service_name\"}[$__rate_interval])) by (le, beast))",
     "legendFormat": "65th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{service_name=~\"$service_name\"}[$__rate_interval])) by (le, beast))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(traces_spanmetrics_latency_bucket{service_name=~\"$service_name\"}[$__rate_interval])) by (le, beast))",
     "legendFormat": "25th Percentile"
    },
    {
     "expr": "sum(rate(traces_spanmetrics_latency_sum{job=\"span-metrics\", service_name=~\"$service_name\"}[5m])) / sum(rate(traces_spanmetrics_latency_count{job=\"span-metrics\", service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Average [5m]"
    }
   ]
  }
 ]
}