{
 "title": "RED dashboard",
 "tags": [
  "terraform",
  "red-method"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\".*grafana/tns.*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# The RED Method\n\nThis TNS demo service dashboard is using the RED Method. A microservices-oriented monitoring philosophy. The RED Method is a good proxy to how happy your customers will be\n\nFor every resource, monitor:\n\n- Rate (the number of requests per second)\n- Errors (the number of those requests that are failing)\n- Duration (the amount of time those requests take)\n\n[Read More...](https://grafana.com/blog/2018/08/02/the-red-method-how-to-instrument-your-services/)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service graph",
   "type": "nodeGraph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 7 },
   "targets": [
    {
     "filters": [
      { "id": "a2df73b6", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "serviceMapQuery": "{}"
    }
   ]
  },
  {
   "title": "Current stats",
   "type": "stat",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (service_name)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\"}[5m])))/(sum by (service_name)(increase(traces_spanmetrics_calls_total{status_code!=\"\"}[5m]))) * 100",
     "legendFormat": "{{service_name}}: Error rate"
    },
    {
     "expr": "sum by(service_name) (rate(traces_spanmetrics_calls_total{job=\"span-metrics\", span_kind!=\"SPAN_KIND_UNSPECIFIED\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}: req/s"
    },
    {
     "expr": "sum by(service_name) (rate(traces_spanmetrics_latency_sum{job=\"span-metrics\"}[5m])) / sum by(service_name) (rate(traces_spanmetrics_latency_count{job=\"span-metrics\"}[5m]))",
     "legendFormat": "{{service_name}}: avg/ms"
    }
   ]
  },
  {
   "title": "Load balancer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{job=\"span-metrics\", service_name=\"lb\", span_kind!=\"SPAN_KIND_UNSPECIFIED\"}[$__rate_interval]))",
     "legendFormat": "HTTP Status {{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{job=\"span-metrics\", service_name=\"lb\", span_kind=\"SPAN_KIND_UNSPECIFIED\"}[$__rate_interval]))",
     "legendFormat": "Unspecified"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"lb\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"lb\"}[$__rate_interval])))",
     "legendFormat": "95th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"lb\"}[$__rate_interval])))",
     "legendFormat": "90th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"lb\"}[$__rate_interval])))",
     "legendFormat": "75th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"lb\"}[$__rate_interval])))",
     "legendFormat": "50th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"lb\"}[$__rate_interval])))",
     "legendFormat": "25th Percentile ({{span_kind}})"
    },
    {
     "expr": "sum(rate(traces_spanmetrics_latency_sum{job=\"span-metrics\", service_name=\"lb\"}[5m])) / sum(rate(traces_spanmetrics_latency_count{job=\"span-metrics\", service_name=\"lb\"}[5m]))",
     "legendFormat": "Average [5m]"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum by (service_name)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\", service_name=\"lb\"}[$__rate_interval])))/(sum by (service_name)(increase(traces_spanmetrics_calls_total{status_code!=\"\", service_name=\"lb\"}[$__rate_interval]))) * 100",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Web application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{job=\"span-metrics\", service_name=\"app\", span_kind!=\"SPAN_KIND_UNSPECIFIED\"}[$__rate_interval]))",
     "legendFormat": "HTTP Status {{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{job=\"span-metrics\", service_name=\"app\", span_kind=\"SPAN_KIND_UNSPECIFIED\"}[$__rate_interval]))",
     "legendFormat": "Unspecified"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"app\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"app\"}[$__rate_interval])))",
     "legendFormat": "95th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"app\"}[$__rate_interval])))",
     "legendFormat": "90th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"app\"}[$__rate_interval])))",
     "legendFormat": "75th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"app\"}[$__rate_interval])))",
     "legendFormat": "50th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"app\"}[$__rate_interval])))",
     "legendFormat": "25th Percentile ({{span_kind}})"
    },
    {
     "expr": "sum(rate(traces_spanmetrics_latency_sum{job=\"span-metrics\", service_name=\"app\"}[5m])) / sum(rate(traces_spanmetrics_latency_count{job=\"span-metrics\", service_name=\"app\"}[5m]))",
     "legendFormat": "Average [5m]"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum by (service_name)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\", service_name=\"app\"}[$__rate_interval])))/(sum by (service_name)(increase(traces_spanmetrics_calls_total{status_code!=\"\", service_name=\"app\"}[$__rate_interval]))) * 100",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{job=\"span-metrics\", service_name=\"db\", span_kind!=\"SPAN_KIND_UNSPECIFIED\"}[$__rate_interval]))",
     "legendFormat": "HTTP Status {{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{job=\"span-metrics\", service_name=\"db\", span_kind=\"SPAN_KIND_UNSPECIFIED\"}[$__rate_interval]))",
     "legendFormat": "Unspecified"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"db\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"db\"}[$__rate_interval])))",
     "legendFormat": "95th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"db\"}[$__rate_interval])))",
     "legendFormat": "90th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"db\"}[$__rate_interval])))",
     "legendFormat": "75th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"db\"}[$__rate_interval])))",
     "legendFormat": "50th Percentile ({{span_kind}})"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le, span_kind) (rate(traces_spanmetrics_latency_bucket{job=\"span-metrics\", service_name=\"db\"}[$__rate_interval])))",
     "legendFormat": "25th Percentile ({{span_kind}})"
    },
    {
     "expr": "sum(rate(traces_spanmetrics_latency_sum{job=\"span-metrics\", service_name=\"db\"}[5m])) / sum(rate(traces_spanmetrics_latency_count{job=\"span-metrics\", service_name=\"db\"}[5m]))",
     "legendFormat": "Average [5m]"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum by (service_name)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\", service_name=\"db\"}[$__rate_interval])))/(sum by (service_name)(increase(traces_spanmetrics_calls_total{status_code!=\"\", service_name=\"db\"}[$__rate_interval]))) * 100",
     "legendFormat": "Error rate"
    }
   ]
  }
 ]
}