{
 "title": "Node Exporter / Node Overview",
 "tags": [
  "linux-node-integration",
  "terraform"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(node_uname_info{sysname!=\"Darwin\", job=\"integrations/node_exporter\", }, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(node_uname_info{job=\"integrations/node_exporter\", job=~\"$job\",}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   {
    "name": "unit",
    "label": "Systemd Unit",
    "query": "label_values({job=~\"$job\",instance=~\"$instance\"}, unit)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Kernel version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_os_info{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (instance) (node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total swap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Root mount size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\", mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Total CPU utilisation percent.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count by (instance) (count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Total CPU utilisation percent.",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\", mode=~\"idle|iowait|steal\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})\n) * 100\n",
     "legendFormat": "cpu {{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "System load average over the previous 1, 5, and 15 minute ranges. A measurement of how many processes are waiting for CPU cycles. The maximum number is the number of CPU cores for the node.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (node_load1{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "1m load average"
    },
    {
     "expr": "avg by (instance) (node_load5{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "5m load average"
    },
    {
     "expr": "avg by (instance) (node_load15{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count by (instance) (node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "Total memory utilisation.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Used: The amount of physical memory currently in use by the system.\nCached: The amount of physical memory used for caching data from disk. The Linux kernel uses available memory to cache data that is read from or written to disk. This helps speed up disk access times.\nFree: The amount of physical memory that is currently not in use.\nBuffers: The amount of physical memory used for temporary storage of data being transferred between devices or applications.\nAvailable: The amount of physical memory that is available for use by applications. This takes into account memory that is currently being used for caching but can be freed up if needed.\n",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"}\n-\n  node_memory_MemFree_bytes{job=~\"$job\",instance=~\"$instance\"}\n-\n  node_memory_Buffers_bytes{job=~\"$job\",instance=~\"$instance\"}\n-\n  node_memory_Cached_bytes{job=~\"$job\",instance=~\"$instance\"}\n)\n",
     "legendFormat": "Memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory available"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory total"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Disk read/writes in bytes, and total IO seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{device}} io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "description": "Disk utilisation in percent, by mountpoint. Some duplication can occur if the same filesystem is mounted in multiple locations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=~\"$job\",instance=~\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Network transmitted and received (bits/s)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} received"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} transmitted"
    }
   ]
  },
  {
   "title": "Network Errors and Dropped Packets",
   "type": "timeseries",
   "description": "errors received: Total number of bad packets received on this network device. This counter must include events counted by rx_length_errors, rx_crc_errors, rx_frame_errors and other errors not otherwise counted.\n\nerrors tranmitted: Total number of transmit problems. This counter must include events counter by tx_aborted_errors, tx_carrier_errors, tx_fifo_errors, tx_heartbeat_errors, tx_window_errors and other errors not otherwise counted.\n\ndrops received: Number of packets received but not processed, e.g. due to lack of resources or unsupported protocol. For hardware interfaces this counter may include packets discarded due to L2 address filtering but should not include packets dropped by the device due to buffer exhaustion which are counted separately in rx_missed_errors (since procfs folds those two counters together).\n\ndrops tranmitted: Number of packets dropped on their way to transmission, e.g. due to lack of resources.\n\nhttps://docs.kernel.org/networking/statistics.html\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} errors received"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} errors tranmitted"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} drops received"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} drops transmitted"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors in system logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{level=~\"err|crit|alert|emerg\",unit=~\"$unit\", job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "{filename=~\"/var/log/syslog*|/var/log/messages*\", job=~\"$job\",instance=~\"$instance\"} |~\".+(?i)error(?-i).+\""
    }
   ]
  },
  {
   "title": "authlog",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "{unit=\"ssh.service\", job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "{filename=~\"/var/log/auth.log|/var/log/secure\", job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Kernel logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "{transport=\"kernel\", job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "{filename=\"/var/log/kern.log\", job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "All system logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "{transport!=\"\", job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "{filename!=\"\", job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  }
 ]
}