#!/bin/bash

set -o errexit
set -o nounset

function_get_cidr() {
  github_actions_cidr=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/meta | jq '.actions')
  echo "${github_actions_cidr}"
}
