#!/bin/bash

source ./lib/colors
source ./lib/github-meta-info

set -o errexit
set -o nounset

status_tfplan="0"
tf_log=""

# GitActionsCIDR commented because aws have a limit of 40 entries, with free runner there is no way to get the egress IP to allow public connections to EKS clusters
# git_actions_cidr=$(function_get_cidr)
# git_actions_cidr="0.0.0.0/0"

color_echo_blue "Planning with Terraform..."
terraform init -backend=true -backend-config="global/backend.hcl" || status_tfplan="1" && \
export TF_VAR_SSH_PRIVATE_KEY="" && \
export TF_VAR_AWS_RDS_PASSWORD="" && \
export TF_VAR_ANSIBLE_VAULT_PASSWORD="" && \
export TF_VAR_ADMIN_USER_ARN="" && \
export TF_VAR_ADMIN_USER_NAME="" && \
export TF_VAR_ARGO_GITHUB_SSO_SECRET_KEY="" && \
# export TF_VAR_GITHUB_ACTIONS_CIDR=${git_actions_cidr} && \
export TF_LOG=${tf_log} && \
terraform plan -var-file="global/terraform.tfvars" || status_tfplan="1" && \
unset TF_VAR_SSH_PRIVATE_KEY && \
unset TF_VAR_AWS_RDS_PASSWORD && \
unset TF_VAR_ANSIBLE_VAULT_PASSWORD && \
unset TF_VAR_ADMIN_USER_ARN && \
unset TF_VAR_ADMIN_USER_NAME && \
unset TF_VAR_ARGO_GITHUB_SSO_SECRET_KEY && \
# unset TF_VAR_GITHUB_ACTIONS_CIDR && \
unset TF_LOG

if [[ "${status_tfplan}" != "0" ]]; then
    color_echo_red "...Terraform plan failed. Maybe your user don't have all the access needed to execute this..."
    exit 0
fi
color_echo_green "...Terraform plan succeeded."
exit 0