#!/bin/bash

source ./lib/colors

set -o errexit
set -o nounset

status_tflint="0"

TFLINT=$(command -v tflint)

color_echo_blue "Linting with TFLint..."
git add . && \
terramate run --changed "${TFLINT}" --init || status_tflint="1"
terramate run --changed "${TFLINT}" --module -f compact || status_tflint="1"
if [[ "${status_tflint}" != "0" ]]; then
    color_echo_red "...TFLint failed."
    exit 1
fi
color_echo_green "...TFLint succeeded."
