#!/bin/bash

source ./hooks/colors.sh

set -o errexit
set -o nounset

status_tflint="0"
status_checkov="0"
status_tfsec="0"
status_tfplan="0"
status_tffmt="0"

diff_lines=$(diff hooks/pre-push .git/hooks/pre-push | wc -l)
if [ $diff_lines != 0 ]; then
  cp hooks/pre-push .git/hooks/pre-push
  chmod +x .git/hooks/pre-push
  color_echo_red "Pre-push hook is out of date, please push your changes again."
  exit 1
fi

color_echo_blue "Checking and installing dependencies..."

if [ $(command -v checkov) = "" ]; then
    color_echo_blue "Checkov not found, installing..."
    pip install -r hooks/requirements.txt
    color_echo_green "Checkov installed..."
else
    color_echo_green "Checkov already installed..."
fi

if [ $(command -v tflint) = "" ]; then
    color_echo_blue "TFLint not found, installing..."
    chmod +x hooks/install_tflint.sh
    ./hooks/install_tflint.sh
    color_echo_green "TFLint installed..."
else
    color_echo_green "TFLint already installed..."
fi

if [ $(command -v tfsec) = "" ]; then
    color_echo_blue "TFSec not found, installing..."
    chmod +x hooks/install_tfsec.sh
    ./hooks/install_tfsec.sh
    color_echo_green "TFSec installed..."
else
    color_echo_green "TFSec already installed..."
fi

CHECKOV=$(command -v checkov)
TFLINT=$(command -v tflint)
TFSEC=$(command -v tfsec)
TERRAFORM=$(command -v terraform)

color_echo_blue "Linting with Checkov..."
"${CHECKOV}" --directory . --var-file global/terraform.tfvars --skip-path .github/ --framework terraform || status_checkov="1"
if [[ "${status_checkov}" != "0" ]]; then
    color_echo_red "...Checkov failed."
    exit 1
fi
color_echo_green "...Checkov succeeded."

color_echo_blue "Linting with TFLint..."
"${TFLINT}" --init
"${TFLINT}" --var-file=./global/terraform.tfvars --module || status_tflint="1"
if [[ "${status_tflint}" != "0" ]]; then
    color_echo_red "...TFLint failed."
    exit 1
fi
color_echo_green "...TFLint succeeded."

color_echo_blue "Linting with TFSec..."
#TODO: Remove soft-fail parameter and check every alert
"${TFSEC}" . --tfvars-file global/terraform.tfvars --soft-fail || status_tfsec="1"

if [[ "${status_tfsec}" != "0" ]]; then
    color_echo_red "...TFSec failed."
    exit 1
fi
color_echo_green "...TFSec succeeded with soft-fail parameter."

color_echo_blue "Formating check with Terraform..."
terraform fmt -check || status_tffmt="1"
if [[ "${status_tffmt}" != "0" ]]; then
    color_echo_red "...Terraform format check failed."
    exit 1
fi
color_echo_green "...Terraform format check succeeded."

color_echo_blue "Planning with Terraform..."
make plan || status_tfplan="1"
if [[ "${status_tfplan}" != "0" ]]; then
    color_echo_red "...Terraform plan failed. Maybe your user don't have all the access needed to execute this..."
    exit 0
fi
color_echo_green "...Terraform plan succeeded."
exit 0