{
 "title": "Synthetic Monitoring DNS",
 "tags": [
  "synthetic-monitoring",
  "terraform"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "probe",
    "query": {
     "query": "label_values(sm_check_info{check_name=\"dns\"},probe)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(sm_check_info{check_name=\"dns\", probe=~\"$probe\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(sm_check_info{check_name=\"dns\", job=\"$job\", probe=~\"$probe\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Error rate by probe",
   "type": "geomap",
   "description": "What's the error percentage for each probe that is observing the given target.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(\n  1 - (\n    sum by (probe, geohash)\n    (\n      rate(probe_all_success_sum{instance=\"$instance\", job=\"$job\"}[$__range])\n     *\n      on (instance, job, probe, config_version)\n      group_left(geohash)\n      max by (instance, job, probe, config_version, geohash)\n      (\n        sm_check_info{instance=\"$instance\", job=\"$job\"}\n      )\n    )\n    /\n    sum by (probe, geohash)\n    (\n      rate(probe_all_success_count{instance=\"$instance\", job=\"$job\"}[$__range])\n        *\n      on (instance, job, probe, config_version)\n      group_left(geohash)\n      max by (instance, job, probe, config_version, geohash)\n      (\n        sm_check_info{instance=\"$instance\", job=\"$job\"}\n      )\n    )\n  )\n)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The fraction of time the target was up during the whole period.",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "# find the average uptime over the entire time range evaluating 'up' in 5 minute windows\navg_over_time(\n  (\n    # the inner query is going to produce a non-zero value if there was at least one successful check during the 5 minute window\n    # so make it a 1 if there was at least one success and a 0 otherwise\n    ceil(\n      # the number of successes across all probes\n      sum by (instance, job) (increase(probe_all_success_sum{instance=\"$instance\", job=\"$job\"}[5m]))\n      /\n      # the total number of times we checked across all probes\n      (sum by (instance, job) (increase(probe_all_success_count{instance=\"$instance\", job=\"$job\"}[5m])) + 1) # + 1 because we want to make sure it goes to 1, not 2\n    )\n  )\n  [$__range:5m]\n)"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "stat",
   "description": "The percentage of all the checks that have succeeded during the whole time period.",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(probe_all_success_sum{instance=\"$instance\", job=\"$job\", probe=~\"$probe\"}[$__range])\n   )\n/\nsum(\n  increase(probe_all_success_count{instance=\"$instance\", job=\"$job\", probe=~\"$probe\"}[$__range])\n   )"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "stat",
   "description": "The average time to receive an answer across all the checks during the whole time period.",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(probe_all_duration_seconds_sum{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Answer Records",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_answer_rrs{probe=~\"$probe\",instance=\"$instance\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "description": "How often is the target checked?",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (frequency) (\n  topk(\n    1,\n    sm_check_info{instance=\"$instance\", job=\"$job\", probe=~\"$probe\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Error Rate : $probe ⮕ $job / $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "  1 - (\n    sum(\n      rate(probe_all_success_sum{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])\n        )\n    /\n    sum(\n      rate(probe_all_success_count{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])\n      )\n  )",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Response latency by probe",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_dns_duration_seconds{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"}) by (probe)",
     "legendFormat": "{{probe}}"
    }
   ]
  },
  {
   "title": "Resource records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(probe_dns_answer_rrs{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "Answer Records"
    },
    {
     "expr": "avg(probe_dns_authority_rrs{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "Authority Records"
    },
    {
     "expr": "avg(probe_dns_additional_rrs{probe=~\"$probe\", instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "Additional Records"
    }
   ]
  },
  {
   "title": "Error logs for $probe: $instance",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{probe=~\"$probe\", instance=\"$instance\", job=\"$job\", probe_success=\"0\"}"
    }
   ]
  }
 ]
}