name: Checkov
on:
  workflow_call:

jobs:
  checkov:
    name: Checkov validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
        continue-on-error: true
