name: Generate terraform docs
on: 
  workflow_call:
    secrets:
      GITHUBREF:
        required: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: GH_TOKEN
      if: env.GH_TOKEN == ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV

    - uses: actions/checkout@v3
      with:
        ref: ${{ secrets.GITHUBREF }}
        token: ${{ env.GH_TOKEN }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        find-dir: .
        output-file: README.md
        output-method: inject
        git-commit-message: "[skip actions] terraform-docs: automated action"
        git-push: "true"
