name: Generate terraform docs
on:
  workflow_run:
    workflows: ["Terraform plan (Development)"]
    types: 
      - completed
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        recursive: true
        output-file: README.md
        output-method: inject
        git-push: "true"