name: Execute external script

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Script to be executed'
        required: true
        default: ""
    branches: [development]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GRAFANA_CLOUD_API_KEY: ${{ secrets.GRAFANA_CLOUD_TERRAFORM_TOKEN }}
  TF_VAR_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  TF_VAR_AWS_RDS_PASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
  TF_VAR_ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
  TF_VAR_ADMIN_USER_ARN: ${{ secrets.ADMIN_USER_ARN }}
  TF_VAR_ADMIN_USER_NAME: ${{ secrets.ADMIN_USER_NAME }}
  TF_VAR_ARGO_GITHUB_SSO_SECRET_KEY: ${{ secrets.ARGO_GITHUB_SSO_SECRET_KEY }}
  TF_VAR_CROSSPLANE_AWS_CREDENTIALS_CONTENT: ${{ secrets.CROSSPLANE_AWS_CREDENTIALS_CONTENT }}
  TF_VAR_GF_AUTH_GITHUB_CLIENT_ID: ${{ secrets.GF_AUTH_GITHUB_CLIENT_ID }}
  TF_VAR_GF_AUTH_GITHUB_CLIENT_SECRET: ${{ secrets.GF_AUTH_GITHUB_CLIENT_SECRET }}
  TF_VAR_GF_SECURITY_ADMIN_USER: ${{ secrets.GF_SECURITY_ADMIN_USER }}
  TF_VAR_GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
  TF_VAR_GRAFANA_CLOUD_METRICSUSER: ${{ secrets.GRAFANA_CLOUD_METRICSUSER }}  
  TF_VAR_GRAFANA_CLOUD_LOGSUSER: ${{ secrets.GRAFANA_CLOUD_LOGSUSER }}
  TF_VAR_GRAFANA_CLOUD_TOKEN: ${{ secrets.GRAFANA_CLOUD_TOKEN }}
  TF_WARN_OUTPUT_ERRORS: 1

jobs:
  external-script:
    name: 'External script execution'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install boto3 and other packages
        run: pip install boto3==1.26.114

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.18.0'

      - name: Terramate Setup
        run: GOBIN=/usr/local/bin/ go install github.com/mineiros-io/terramate/cmd/terramate@v0.2.18

      - name: Execute
        id: execute-script
        run: |
          ${{ inputs.script }}
