name: Terraform plan

on: 
  pull_request:
    branches: [development]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  TF_VAR_AWS_RDS_PASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
  TF_VAR_ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
  TF_VAR_ADMIN_USER_ARN: ${{ secrets.ADMIN_USER_ARN }}
  TF_VAR_ADMIN_USER_NAME: ${{ secrets.ADMIN_USER_NAME }}
  TF_VAR_ARGO_GITHUB_SSO_SECRET_KEY: ${{ secrets.ARGO_GITHUB_SSO_SECRET_KEY }}
  TF_VAR_CROSSPLANE_AWS_CREDENTIALS_CONTENT: ${{ secrets.CROSSPLANE_AWS_CREDENTIALS_CONTENT }}

jobs:
  sonarcloud:
    name: Security check
    uses: kaio6fellipe/terraform-devops/.github/workflows/sonar.yml@development
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tflint:
    name: Lint check
    uses: kaio6fellipe/terraform-devops/.github/workflows/tflint.yml@development
    # uses: ./.github/workflows/tflint.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  tfsec:
    name: Terraform Security check
    uses: kaio6fellipe/terraform-devops/.github/workflows/tfsec.yml@development
    # uses: ./.github/workflows/tfsec.yml

  checkov:
    name: Checkov Security check
    uses: kaio6fellipe/terraform-devops/.github/workflows/checkov.yml@development

  plan:
    name: 'Terraform plan'
    needs: [tflint]
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # GitActions CIDR commented because aws have a limit of 40 entries, with free runner there is no way to get the egress IP to allow public connections to EKS clusters
      # Ref: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
      # - name: Get GitActions egress CIDR blocks
      #   run: |
      #     source ./lib/github-meta-info
      #     EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
      #     echo "TF_VAR_GITHUB_ACTIONS_CIDR<<$EOF" >> $GITHUB_ENV
      #     function_get_cidr >> $GITHUB_ENV
      #     echo "$EOF" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.18.0'

      - name: Terramate Setup
        run: GOBIN=/usr/local/bin/ go install github.com/mineiros-io/terramate/cmd/terramate@v0.2.18

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: true

      - name: Terramate Fmt
        id: tm-fmt
        run: terramate fmt --check
        continue-on-error: true

      - name: List all Stacks
        run: terramate list

      - name: Terramate Init
        id: init
        run: terramate run --changed terraform init -backend=true

      - name: Terramate Validate
        id: validate
        run: terramate run --changed terraform validate -no-color

      - name: Terramate Plan
        id: plan
        run: terramate run --changed terraform plan

      - name: Post Plan on PR
        if: always() && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
        uses: robburger/terraform-pr-commenter@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_IN_AUTOMATION: true
        with:
          commenter_type: plan
          commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
          commenter_exitcode: ${{ steps.plan.outputs.exitcode }}

      # - uses: actions/github-script@v6
      #   if: github.event_name == 'pull_request'
      #   env:
      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const output = `#### Terramate Format and Style 🖌\`${{ steps.fmt.outcome }}\`
      #       #### Terramate Initialization ⚙️\`${{ steps.init.outcome }}\`
      #       #### Terramate Validation 🤖\`${{ steps.validate.outcome }}\`
      #       #### Terramate Plan 📖\`${{ steps.plan.outcome }}\`
      #       
      #       <details><summary>Show Plan</summary>
      #       
      #       \`\`\`${process.env.PLAN}\`\`\`
      #       
      #       </details>
      #       
      #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
      #       
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: output
      #       })

      # - name: Terramate Plan Status
      #   if: steps.plan.outcome == 'failure'
      #   run: exit 1
