name: TFLint
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  tflint:
    name: "TFLint validation"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source code
      with:
          fetch-depth: 0

    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: v0.42.2

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.4

    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.18.0'

    - name: Terramate Setup
      run: GOBIN=/usr/local/bin/ go install github.com/mineiros-io/terramate/cmd/terramate@v0.2.18

    - name: Show version
      run: tflint --version

    - name: Terramate Init
      run: terramate run --changed terraform init -backend=true

    - name: Init TFLint
      run: terramate run --changed tflint --init 
      
    - name: Run TFLint
      run: terramate run --changed tflint --module -f compact
