name: Terraform Security Check

on:
  workflow_call:

jobs:
  tfsec:
    name: TFSec validation
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Run tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          #TODO: Remove soft-fail parameter and check every alert
          tfsec_args: --tfvars-file global/terraform.tfvars --soft-fail
          github_token: ${{ secrets.GITHUB_TOKEN }} 
