{
 "title": "Grafana Agent Overview",
 "tags": [
  "grafana-agent-integration",
  "terraform"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(agent_build_info, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(agent_build_info{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Instances",
   "type": "table-old",
   "description": "General statistics of running grafana agent instances.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (instance, version) (agent_build_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "max by (instance) (time() - process_start_time_seconds{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Prometheus Discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Target Sync",
   "type": "timeseries",
   "description": "Actual interval to sync the scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance, scrape_job) * 1e3",
     "legendFormat": "{{instance}}/{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "timeseries",
   "description": "Discovered targets by prometheus service discovery.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (prometheus_sd_discovered_targets{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Prometheus Retrieval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Scrape Interval Duration",
   "type": "timeseries",
   "description": "Actual intervals between scrapes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) / rate(prometheus_target_interval_length_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) * 1e3",
     "legendFormat": "{{instance}} {{interval}} configured"
    }
   ]
  },
  {
   "title": "Scrape failures",
   "type": "timeseries",
   "description": "Shows all scrape failures (sample limit exceeded, duplicate, out of bounds, out of order).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "exceeded sample limit: {{job}}"
    },
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "duplicate timestamp: {{job}}"
    },
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "out of bounds: {{job}}"
    },
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "out of order: {{job}}"
    }
   ]
  },
  {
   "title": "Appended Samples",
   "type": "timeseries",
   "description": "Total number of samples appended to the WAL.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, instance_group_name) (rate(agent_wal_samples_appended_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{instance_group_name}}"
    }
   ]
  }
 ]
}