{
 "title": "Grafana Agent Tracing Pipeline",
 "tags": [
  "grafana-agent-integration",
  "terraform"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(agent_build_info, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(agent_build_info{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Write / Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Accepted spans",
   "type": "timeseries",
   "description": "Number of spans successfully pushed into the pipeline.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traces_receiver_accepted_spans{job=~\"$job\", instance=~\"$instance\",receiver!=\"otlp/lb\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - {{ receiver }}/{{ transport }}"
    }
   ]
  },
  {
   "title": "Refused spans",
   "type": "timeseries",
   "description": "Number of spans that could not be pushed into the pipeline.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traces_receiver_refused_spans{job=~\"$job\", instance=~\"$instance\",receiver!=\"otlp/lb\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - {{ receiver }}/{{ transport }}"
    }
   ]
  },
  {
   "title": "Exported spans",
   "type": "timeseries",
   "description": "Number of spans successfully sent to destination.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traces_exporter_sent_spans{job=~\"$job\", instance=~\"$instance\",exporter!=\"otlp\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - {{ exporter }}"
    }
   ]
  },
  {
   "title": "Exported failed spans",
   "type": "timeseries",
   "description": "Number of spans failed to send.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traces_exporter_send_failed_spans{job=~\"$job\", instance=~\"$instance\",exporter!=\"otlp\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - {{ exporter }}"
    }
   ]
  },
  {
   "title": "Received spans",
   "type": "timeseries",
   "description": "Number of spans successfully pushed into the pipeline.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traces_receiver_accepted_spans{job=~\"$job\", instance=~\"$instance\",receiver!=\"otlp/lb\"}[$__rate_interval]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(rate(traces_receiver_refused_spans{job=~\"$job\", instance=~\"$instance\",receiver!=\"otlp/lb\"}[$__rate_interval])) ",
     "legendFormat": "Refused"
    }
   ]
  },
  {
   "title": "Exported spans",
   "type": "timeseries",
   "description": "Number of spans successfully sent to destination.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traces_exporter_sent_spans{job=~\"$job\", instance=~\"$instance\",exporter!=\"otlp\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(traces_exporter_send_failed_spans{job=~\"$job\", instance=~\"$instance\",exporter!=\"otlp\"}[$__rate_interval]))",
     "legendFormat": "Send failed"
    }
   ]
  },
  {
   "title": "Load balancing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load-balanced spans",
   "type": "timeseries",
   "description": "Number of load balanced spans.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traces_loadbalancer_backend_outcome{job=~\"$job\", instance=~\"$instance\", cluster=~\"$cluster\",namespace=~\"$namespace\",success=\"true\",container=~\"$container\",pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of peers",
   "type": "timeseries",
   "description": "Number of tracing peers.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traces_loadbalancer_num_backends{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Received spans",
   "type": "timeseries",
   "description": "Number of spans successfully pushed into the pipeline.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traces_receiver_accepted_spans{job=~\"$job\", instance=~\"$instance\",receiver=\"otlp/lb\"}[$__rate_interval]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(rate(traces_receiver_refused_spans{job=~\"$job\", instance=~\"$instance\",receiver=\"otlp/lb\"}[$__rate_interval])) ",
     "legendFormat": "Refused"
    }
   ]
  },
  {
   "title": "Exported spans",
   "type": "timeseries",
   "description": "Number of spans successfully sent to destination.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traces_exporter_sent_spans{job=~\"$job\", instance=~\"$instance\",exporter=\"otlp\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(traces_exporter_send_failed_spans{job=~\"$job\", instance=~\"$instance\",exporter=\"otlp\"}[$__rate_interval]))",
     "legendFormat": "Send failed"
    }
   ]
  }
 ]
}