{
 "title": "Grafana Agent Logs",
 "tags": [
  "grafana-agent-integration",
  "terraform"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(agent_build_info, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(agent_build_info{job=~\"$job\"}, instance)"
   },
   { "name": "text_filter", "label": "Text Filter" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Log Lines",
   "type": "stat",
   "description": "Shows the total number of log lines.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\"} |= \"$text_filter\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "description": "Shows the number of log lines with a log type of warning.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\", level=\"warn\"} |= \"$text_filter\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Shows the number of log lines with a log type of error.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\", level=\"error\"} |= \"$text_filter\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "stat",
   "description": "Shows number of errors as a percentage of total log lines.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( count_over_time({job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\", level=\"error\"} |= \"$text_filter\" [$__interval]) ) / sum( count_over_time({job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\"} [$__interval]) )"
    }
   ]
  },
  {
   "title": "Bytes Used",
   "type": "stat",
   "description": "Shows total number of bytes used by the logs.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\"} |= \"$text_filter\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Historical Logs / Warnings / Errors",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\"} |= \"$text_filter\" [$__interval]))"
    },
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\", level=\"warn\"} |= \"$text_filter\" [$__interval]))"
    },
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\", level=\"error\"} |= \"$text_filter\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Info",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "{job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\", level=\"info\"} |= \"$text_filter\""
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Errors",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "{job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\", level=\"error\"} |= \"$text_filter\""
      }
     ]
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Warnings",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "{job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\", level=\"warn\"} |= \"$text_filter\""
      }
     ]
    }
   ]
  },
  {
   "title": "Complete Log File",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Full Log File",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "{job=~\"$job\", instance=~\"$instance\", unit=~\"grafana-agent.service\"} |= \"$text_filter\""
      }
     ]
    }
   ]
  }
 ]
}