{
 "title": "Grafana Agent Remote Write",
 "tags": [
  "grafana-agent-integration",
  "terraform"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(agent_build_info, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(agent_build_info{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Timestamps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Highest Timestamp In vs. Highest Timestamp Sent",
   "type": "timeseries",
   "description": "Highest timestamp that has come into the remote storage via the Appender interface, in seconds since epoch.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n            (\n              prometheus_remote_storage_highest_timestamp_in_seconds{job=~\"$job\", instance=~\"$instance\"}\n              -\n              ignoring(url, remote_name) group_right(pod)\n              prometheus_remote_storage_queue_highest_sent_timestamp_seconds{job=~\"$job\", instance=~\"$instance\"}\n            )\n          ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency Over Rate Interval",
   "type": "timeseries",
   "description": "Rate of duration of send calls to the remote storage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_sent_batch_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) / rate(prometheus_remote_storage_sent_batch_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "mean {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "p99 {{instance}}"
    }
   ]
  },
  {
   "title": "Samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Samples In Rate Over Rate Interval",
   "type": "timeseries",
   "description": "Rate of total number of samples appended to the WAL.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(agent_wal_samples_appended_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Samples Out Rate Over Rate Interval",
   "type": "timeseries",
   "description": "Rate of total number of samples sent to remote storage.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_succeeded_samples_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) or rate(prometheus_remote_storage_samples_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending Samples",
   "type": "timeseries",
   "description": "The number of samples pending in the queues shards to be sent to the remote storage.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_samples_pending{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dropped Samples",
   "type": "timeseries",
   "description": "Total number of samples which were dropped after being read from the WAL before being sent via remote write, either via relabelling or unintentionally because of an unknown reference ID.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_dropped_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Samples",
   "type": "timeseries",
   "description": "Total number of samples which failed on send to remote storage, non-recoverable errors.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_failed_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Retried Samples",
   "type": "timeseries",
   "description": "Total number of samples which failed on send to remote storage but were retried because the send error was recoverable.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_samples_retried_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Shards",
   "type": "timeseries",
   "description": "The number of shards used for parallel sending to the remote storage.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Shards",
   "type": "timeseries",
   "description": "The maximum number of shards that the queue is allowed to run.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_max{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Min Shards",
   "type": "timeseries",
   "description": "The minimum number of shards that the queue is allowed to run.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_min{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Desired Shards",
   "type": "timeseries",
   "description": "The number of shards that the queues shard calculation wants to run based on the rate of samples in vs. samples out.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_desired{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Shard Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shard Capacity",
   "type": "timeseries",
   "description": "The capacity of each shard of the queue used for parallel sending to the remote storage.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shard_capacity{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Remote Write Current Segment",
   "type": "timeseries",
   "description": "Current segment the WAL watcher is reading records from.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "prometheus_wal_watcher_current_segment{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Misc. Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Enqueue Retries",
   "type": "timeseries",
   "description": "Total number of times enqueue has failed because a shards queue was full.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_enqueue_retries_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}